id = "ca65"
name = "CA65 Assembly"
version = "0.0.1"
schema_version = 1
authors = ["techwritescode <10032418+techwritescode@users.noreply.github.com>"]
description = "Language support for CA65"
repository = "https://github.com/techwritescode/ca65-zed"

[grammars.ca65]
repository = "https://github.com/techwritescode/tree-sitter-ca65"
commit = "9e73befb5c3c6852f905964c22740c9605b03af8"

[language_servers.ca65]
name = "CA65 LSP"
language = "CA65"
